### ISSUE TITLE
Tracking module

### ISSUE THREAD

**Issue by gitttt-1234** [talmolab/sleap-nn#53]
Tracking modules are required to track instances across frames in a multi-instance setting by assigning unique IDs to each instance across frames.

# Tracking components

Steps involved in tracking:

- _Candidate generation_: Two methods are supported - Fixed window (consider instances from the last N frames) and Tracking local queues (consider the last N instances for each track).
- _Candidate updating_: For some trackers, we can use previous frames to update the current detections. This can be done in the Flow Shift approach (core in SLEAP) which uses optical flow to update the positions of previous detections using differences between the images (but this is an expensive computation which needs to be carefully implemented and parallelized). It can also be done using motion models, which don't use the pixels but leverage the trajectory so far to predict where instances should be in the future, e.g., using a Kalman Filter.
- _Feature representation_: Feature representation of past N instances for each track - either an embedding of cropped image around each instance (visual feature), the bounding box coordinates, or centroids, or the poses as a feature.
- _Scoring method_: Method to compute association score between instances from the current frame and the previous tracks. For visual feature vectors, this might be cosine similarity, for bounding boxes it could be IOU, for centroids it could be Euclidean distance, and for poses it could be OKS.
- _Scoring reduction_: If there are multiple detections associated with the same track, then how are the multiple scores aggregated and reduced? You could take the mean, max, or weighted sum (weights = confidences, time, or some combination).
- _Track assignment_: Assign track id to current frame's predicted instances. Once you have scores in the form of an association/cost matrix, then how are assignments made? It could be greedily (bad), Hungarian (better), or ILP (best, but slow and complex).
- _Handling special cases_: When do spawn new tracks or mark some as stale? How do we handle variable numbers of tracks (e.g., when animals can leave and re-enter the FOV)? Do we have special logic for ReID?
- _Post-processing_: After initial tracks are formed, how are track fragments stitched together, if at all? How can we impose more explicit constraints like maximum displacement, maximum gaps, and confidence thresholds?

# Tracker class - Implementation
The tracker module has the following attributes: 

1. `max_tracks`: The maximum number of new tracks that can be created.
2. `window_size`: number of previous frames to compare the current predicted instance with.
3. `instance_score_threshold`: threshold for creating new tracks.
4. `candidates_method`: "fixed_window" or "track_local_queue". Default: `fixed_window`.
5. `track_queue`: dictionary that stores the past frames of all the tracks identified so far. {`track_id_0`: np.array(`window_size` instances)}
6.  `use_visual_features`: Boolean to indicate whether features should be the images. If False, instances are used as features

```bash                      
    ├── tracking
          ├── candidates                    # Classes to handle the tracker update queue operations
                 ├── fixed_window.py
                 ├── local_queues.py
          ├── track_instance.py              # `TrackInstance` data structure
          ├── tracker.py                     # `Tracker` class 
          ├── utils.py                       # Helper functions for scoring and assignment
    └── 
```
`TrackInstance` is the base data structure for tracking. This would have the following attributes: original `np.array` instance, feature representation for the instance, assigned track id (None if untracked). All entities in the tracker queue will be an instance of `TrackInstance` class.

`FixedWindowCandidates` and `LocalQueueCandidates` are two classes defined in `fixed_window.py` and `local_queues.py` respectively. These modules are responsible for handling track ID creation/ deletions and candidate updates to respective track IDs. The `tracker_queue` in `Tracker` object is an instance of one of the two candidate classes.

Tracker object is initialized in the [Predictor.from_trained_models()](https://github.com/talmolab/sleap-nn/blob/4655651bcbc102c54f348aab4db1d55347e997af/sleap_nn/inference/predictors.py#L384) along with initializing the model (tracker would be an attribute of the Predictor modules). `Tracker.track` is called from [inference.predictors.Predictor._make_labelled_frames_from_generator()](https://github.com/talmolab/sleap-nn/blob/4655651bcbc102c54f348aab4db1d55347e997af/sleap_nn/inference/predictors.py#L282) by passing `sio.PredictedInstance` object one at a time. `Tracker.track()` returns the `sio.PredictedInstance` object with a track id associated to each of the instances.  

```py
import attrs
from typing import Dict

@attrs.define
class Tracker():
    tracker_queue: Union[FixedWindowCandidates, LocalQueueCandidates] = {}  
    
    def track(self, untracked_instances: sio.PredictedInstance):
        # Returns `sio.PredictedInstance` object with assigned tracks.

        track_instances = self._get_features(untracked_instances) # get features 

        if self.tracker_queue.not_empty():
              
              # scoring function
              scores = self._get_scores(track_instances)
              
              # track assignment

               # convert the track_instances back to `sio.PredictedInstance`
              new_pred_instances = self._get_predicted_instance(track_instances)

       # update the candidates with the newly tracked instances
       self.tracker_queue.update_candidates(track_instances)
    
        return new_pred_instances 
   
    def _get_features(self, untracked_instances):
        # get feature representation - instances/ embedding (image passed through the a few conv layers). 
        # Returns a list of `TrackInstance` objects (for all the instances in the `untracked_instances` object) with `track_id` set as None.
         return track_instances

    def _get_scores(self, track_instances, scoring_method):
         # Returns a matrix with dim: (num_existing_tracks, len(track_instances))
         # compute score between all pairs of `TrackInstance` objects.
         # Score reduction: mean, max
          
         return scores
   
    def _get_predicted_instance(self, track_instances):
        # Returns `sio.PredictedInstance` from the given list of `TrackInstance` objects.
        return new_pred_instances
   
```

# Roadmap

## MVP for parity

- [x] Simple tracker
  - [x] Candidate generation: Fixed window
  - [x] Feature representation: Poses
  - [x] Scoring method: OKS
  - [x] Scoring reduction: Mean
  - [x] Track assignment: Hungarian
- [x] Candidate generation: Track-local queues
- [x] Candidate updating: Flow shift
- [x] Integration in inference loop

## Next PR
- [ ] Handle stale tracks
- [ ] Post-processing: Track cleaning
- [ ] Images as feature representations

## Next

- [ ] Integration with Ultralytics ByteSORT
- [ ] Integration with idtracker.ai
- [ ] Integration with DREEM
- [ ] Native DeepSORT (requires training for the ReID model)

## Future / research phase

- [ ] Integration with exogenous signals like RFID
- [ ] Explicit specification of visual markers (e.g., ear tags, tail markings, coat coloring)
- [ ] Proper integration of ILPs (e.g., https://github.com/funkelab/motile)
- [ ] Explore use of dense tracking methods for MOT (e.g., PIPs++, TAPNet, etc.)
